In [1]:
max([ i for i in range(10)])


9

In [3]:
m=[ {"a":1,"b":2,"c":5},{"a":1,"b":2,"c":5},{"a":1,"b":2,"c":99}]
max( m )


TypeError: '>' not supported between instances of 'dict' and 'dict'

# func

In [2]:
def sigmoid(x):
    return 1.0/(1+np.e**(-x))

In [ ]:
import itertools

product 笛卡尔积　　（有放回抽样排列）

permutations 排列　　（不放回抽样排列）

combinations 组合,没有重复　　（不放回抽样组合）

combinations_with_replacement 组合,有重复　　（有放回抽样组合）

>> from scipy.special import comb, perm
>> perm(3, 2)
6.0
>> comb(3, 2)
3.0

# matrix

In [ ]:
    先讲一个方阵的对角线下的下三角阵和对角线上的上三角阵提取出来（如果只需要上下三角阵，则去掉tril/triu中的第二个参数）
    上代码(这里使用tril和triu都是返回array形式，还需使用mat转换回矩阵)：
    复制代码

    >>> m = np.mat("1,2,3;4,5,6;7,8,9")
    >>> m
    matrix([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
    >>> L = np.tril(m,-1)
    >>> L
    array([[0, 0, 0],
           [4, 0, 0],
           [7, 8, 0]])
    >>> U = np.triu(m,1)
    >>> U
    array([[0, 2, 3],
           [0, 0, 6],
           [0, 0, 0]])